### ISSUE TITLE
There is no way to remove a task after a `hoodie.task.error` in a worker.js

### ISSUE THREAD

**Issue by boennemann** [hoodiehq/hoodie-task-server#3]
via @louisremi https://github.com/hoodiehq/hoodie-server/issues/323

---

When it receives a new task, my server-side plugin does various things, like querying a third party API or adding documents to a `user/xxxxx` database.
Sometimes one of these "various things" fails. I can detect this error, handle it in any way I please and then propagate it to the client-side using `hoodie.task.error()` (once [hoodie.js#185](https://github.com/hoodiehq/hoodie.js/issues/185) is solved),  but I also want to get rid of the task just like `hoodie.task.success()` does. 

"Ok little task, I saw the error, the client saw the error, now clean after yourself and let's call it a day."

**Comment by louisremi** [comment]
Similarly, my _users DB is crippled with password reset tasks, probably the one that errored because the email was unknown. It would be great if they got cleaned up somehow : )

**Comment by inator** [comment]
I think the latest refractor, which uses the hoodie Store api, now solves this.  The error method now [removes the task doc](https://github.com/hoodiehq/hoodie-task-server/blob/master/api/index.js#L38).
