### ISSUE TITLE
Make .success() and .error() update progress property

### ISSUE THREAD

**Issue by inator** [hoodiehq/hoodie-task-server#40]
As with issue #38, all API methods should push to the taskDoc.progress array property to reflect the task result as follows:

    // On .success
    .progress: [{name: 'success', at: '2017-01-03T21:46:55.688Z', progressData: data }]
  
    // On error
    .progress: [{name: 'error', at: '2017-01-03T21:46:55.688Z', progressData: data }]

This will ensure that the entire lifecycle of a task is captured, including any relevant data cargo, for use by the client.

**Comment by inator** [comment]
Pinging https://github.com/hoodiehq/camp/issues/100 for those interested in giving input on this new feature.

**Comment by mbad0la** [comment]
Hey @inator

Can't seem to understand how this progress updation will be accessible as upon calling the `success` or `error` method, the `taskDoc` is destroyed.

Am I missing something?

If not, I think we should probably have a mechanism to probably push the status from the server to the client, before removing the `taskDoc` from the database.

Or maybe we could persist the `taskDoc` and remove it upon a **progress heartbeat** (Had a discussion about this in #38) if the current progress status is success or errored. 

What do you think?

**Comment by inator** [comment]
@mbad0la -

Actually, this is by design.  The deleted taskDoc still makes its way to the client via sync (part of the store-server/store-client that we leverage) and the properties can be read there.  We do this so taskDocs don't hang around after their full lifecycle.

**Comment by mbad0la** [comment]
Makes sense. Thanks for clearing this up!

**Comment by inator** [comment]
@mbad0la - FYI - we're gonna start relying on the `.progress` property in the `task-client` for detecting `success` and `error`.  That effort is underway now, and I'll expose you to the relevant code ASAP so you have a better idea of how your work here impacts things.  Thanks!

**Comment by inator** [comment]
@mbad0la - please ensure that the object pushed to `taskDoc.progress` includes a `.error` property; `{ ... error: 'passed error' }` when `.error()` is invoked.  The `task-client` will be relying on that being there.  Thanks!

**Comment by mbad0la** [comment]
@inator - Do you mean the last object in the `taskDoc.progress` array?

So a task which errored might have a progress life cycle like `[{ ... }, { ... }, { name: 'error', created_at: timestamp, error: error}]`

**Comment by inator** [comment]
> So a task which errored might have a progress life cycle like [{ .. }, { ...}, { name: 'error', created_at: timestamp, error: error}]

@mbad0la - Exactly!  But to clarify... 

    { name: 'error', at: timestamp, error: errorText }

**Comment by inator** [comment]
@mbad0la - And here's the sort of thing that will happen in the `task-client` code:

    ...
    var lastProgress = changedTaskDoc.progress[changedTaskDoc.progress.length - 1]
    var disposition = lastProgress.name

    // Prevent any EventEmitter thrown Error from affecting the Promise
    process.nextTick(function() {
        state.emitter.emit(disposition, lastProgress.error || null, changedTaskDoc)	
    })
            
    // Resolve or reject
    if (disposition === 'success') return resolve(changedTaskDoc)
    if (disposition === 'error') return reject(new Error(lastProgress.error))
    ...

Just to give you a better idea of how your work fits in. :)

**Comment by mbad0la** [comment]
Thanks @inator! Submitting the PR in a few hours :)
